### ISSUE TITLE
how to install it?

### ISSUE THREAD

**Issue by liamxg** [cwhidden/rspr#11]
@cwhidden @matsen

**Comment by cwhidden** [comment]
As noted in the README:

INSTALLATION

rSPR is a command-line program written in C++. To use it, simply
compile rspr.cpp and execute the resulting program. On systems with
the g++ compiler and make program, the included make file will
compile rspr; simply run `make'.


Are you having difficulty compiling the software?

**Comment by cwhidden** [comment]
You're welcome

**Comment by matsen** [comment]
You're still trying to run this from within R. That can't work.

You need to run this from the command line, e.g. bash.

**Comment by cwhidden** [comment]
Hello,

RSPR is a command line C++ program. First make sure you can compile and run it from the command line following the README instructions.

There is an R interface that was provided by a contributor. This has not been updated in some time so I am unsure of its status but it should work for some situations. However, you still need to compile rspr and make it accessible on your path environment variable. As noted in rspr.r:

############
### Wrappers for the great rpsr (https://github.com/cwhidden/rspr) by Chris Whidden (FHCRC)
### Note that the functions here assume rspr is installed in the system, ie., at /usr/bin/rspr
### Copyleft (or the one to blame): Carvalho, LMF (2015)
### Last update: github is your friend.
############



Best,
Chris

From: Liam ***@***.***>
Date: Tuesday, October 10, 2023 at 8:49 AM
To: cwhidden/rspr ***@***.***>
Cc: Chris Whidden ***@***.***>, Mention ***@***.***>
Subject: Re: [cwhidden/rspr] how to install it? (Issue #11)

https://github.com/cwhidden/rspr/blob/master/R/rspR_examples.r
